# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter
#       Anaconda Inc., Using conda with Travis CI, Conda documentation, https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
#       .travis.yml for gcc-5 compiler support on Travis CI , https://gist.github.com/cotsog/3ce84675af0d74438d91
#       CodeChat, .travis.yml - Travis CI configuration, https://pythonhosted.org/CodeChat/.travis.yml.html
#       Travis CI, Python example (unsupported languages), https://docs.travis-ci.com/user/multi-os/#python-example-unsupported-languages


language : shell

env:
  global:
    - MINICONDA_DOWNLOAD=$HOME/download
    - MINICONDA_PATH=$HOME/miniconda
  matrix:
    - CONDA_PYTHON=3.7.1
    - CONDA_PYTHON=3.7.3
    - CONDA_PYTHON=nightly

os :
  - linux
  - osx

before_cache:
  - rm -rf $MINICONDA_PATH/locks $MINICONDA_PATH/pkgs $MINICONDA_PATH/var $MINICONDA_PATH/conda-meta/history $MINICONDA_PATH/envs/test-environment/conda-meta/history $MINICONDA_PATH/lib/python3.6/__pycache__ $MINICONDA_PATH/lib/python3.7/__pycache__;
  - touch $MINICONDA_PATH/conda-meta/history;

cache :
  directories:
    - $MINICONDA_DOWNLOAD
    - $MINICONDA_PATH

before_install:
  # When C++14 support becomes more clear, consider revision
  # https://docs.travis-ci.com/user/multi-os/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update -qq;
    fi;
  - . ./tests/before_install_nix_win_cache.sh

install:
  # When C++14 support becomes more clear, consider revision
  # https://docs.travis-ci.com/user/multi-os/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get install -qq g++-6;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;
    fi
  - ./tests/install_nix_win_cache.sh

# https://lord.io/blog/2014/travis-multiple-subdirs/
script:
  - pytest -n auto tests/
