# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter
#       Anaconda Inc., Using conda with Travis CI, Conda documentation, https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
#       .travis.yml for gcc-5 compiler support on Travis CI , https://gist.github.com/cotsog/3ce84675af0d74438d91
#       CodeChat, .travis.yml - Travis CI configuration, https://pythonhosted.org/CodeChat/.travis.yml.html
#       Travis CI, Python example (unsupported languages), https://docs.travis-ci.com/user/multi-os/#python-example-unsupported-languages

language: shell

env:
  - CONDA_PYTHON=3.6
  - CONDA_PYTHON=3.7
  - CONDA_PYTHON=nightly

os :
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os : windows
  fast_finish: true

before_cache:
  - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history $HOME/miniconda/envs/test-environment/conda-meta/history $HOME/miniconda/lib/python3.6/__pycache__ $HOME/miniconda/lib/python3.7/__pycache__/c/tools/miniconda3/locks /c/tools/miniconda3/pkgs /c/tools/miniconda3/var /c/tools/miniconda3/conda-meta/history /c/tools/miniconda3/envs/test-environment/conda-meta/history /c/tools/miniconda3/lib/python3.6/__pycache__ /c/tools/miniconda3/lib/python3.7/__pycache__

cache :
  directories:
    - $HOME/download
    - $HOME/miniconda
    - $HOME/AppData/Local/Temp/chocolatey

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_install:
  # https://docs.travis-ci.com/user/multi-os/
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      echo "OS is not Windows";
      if [[ -f $HOME/download/miniconda.sh && $CONDA_PYTHON != "nightly" ]]; then
        echo "miniconda.sh for posix already available";
      else
        echo "miniconda.sh for not posix available";
        mkdir -p $HOME/download;
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          echo "downloading miniconda.sh for linux";
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
        elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          echo "downloading miniconda.sh for osx";
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
        fi;
      fi;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      echo "OS is Windows";
      if [[ -f $HOME/download/miniconda.exe && $CONDA_PYTHON != "nightly" ]]; then
        echo "miniconda.exe for windows already available";
      else
        echo "getting miniconda.exe for windows";
        mkdir --parents $HOME/download;
        curl -o $HOME/download/miniconda.exe "https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Windows-x86_64.exe";
      fi;
    fi;

install:
  # To help debugging
  - echo $TRAVIS_OS_NAME
  - echo $CONDA_PYTHON
  # When C++14 support becomes more clear, consider revision
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;
    fi
  # Set conda path info
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      CONDA_PATH=$HOME/miniconda;
      CONDA_SUB_PATH=$CONDA_PATH/bin;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      CONDA_PATH=/c/tools/miniconda3;
      CONDA_SUB_PATH=$CONDA_PATH/Scripts;
    fi
  # Install miniconda
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      echo "OS is not Windows";
      if [[ -e $CONDA_SUB_PATH/conda && $CONDA_PYTHON != "nightly" ]]; then
        echo "miniconda for posix already available";
      else
        echo "installing miniconda for posix";
        bash $HOME/download/miniconda.sh -b -u -p $HOME/miniconda;
      fi;
    elif  [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      echo "OS is Windows";
      if [[ -e $CONDA_SUB_PATH/conda && $CONDA_PYTHON != "nightly" ]];then
        echo "miniconda for Windows already installed";
      else
        echo "installing miniconda for windows";
        $HOME/download/miniconda.exe /AddToPath:1 /S /D=$HOME/miniconda;
      fi;
    fi
  - export PATH="$CONDA_PATH:$CONDA_SUB_PATH:$PATH";
  # Forget all remembered locations
  - hash -r
  - which conda;
  - conda info -a
  # Conda setup options
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Create or update test environment of python module recipies
  - if [[ ! -d $CONDA_PATH/envs/test-environment ]]; then
      echo "creating test-environment";
      if [[ "$CONDA_PYTHON" == "3.6" ]]; then
        conda env create -n test-environment python=$CONDA_PYTHON -f ./tests/environment.3.6.yml;
      elif [[ "$CONDA_PYTHON" == "3.7" ]]; then
        conda env create -n test-environment python=$CONDA_PYTHON -f ./tests/environment.3.7.yml;
      else
        conda env create -n test-environment python=$CONDA_PYTHON -f ./tests/environment.nightly.yml;
      fi;
    elif [[ -d $CONDA_PATH/envs/test-environment ]]; then
      echo "updating test-environment";
      if [[ "$CONDA_PYTHON" == "3.6" ]]; then
        conda env update -n test-environment python=$CONDA_PYTHON -f ./tests/environment.3.6.yml;
      elif [[ "$CONDA_PYTHON" == "3.7" ]]; then
        conda env update -n test-environment python=$CONDA_PYTHON -f ./tests/environment.3.7.yml;
      else
        conda env update -n test-environment python=$CONDA_PYTHON -f ./tests/environment.nightly.yml;
      fi;
    fi
  - source activate test-environment
  - conda list

script: 
  - cd tests && py.test

notifications:
    email:
        - kangwon.lee.edu@gmail.com
