name: Check Links

on: 
  schedule:
    - cron: '45 01 30 * *'
  pull_request:
  workflow_dispatch:

jobs:
  test_links_utils:
    name: Check links in ipynb
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-xdist requests jupyter lxml numpy matplotlib scipy sympy

    - name: Check links
      run: python -m pytest -n auto ./tests/test_check_links_in_ipynb.py ./utils/tests/
