name: CI

on: [push]

jobs:
  build:
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, ubuntu-16.04, macOS-10.14, macOS-latest]
        anaconda: [3.7.1, 3.7.3, 2019.07, nightly]

    steps:
    - uses: actions/checkout@v1
    - name: build environment
      env:
        CONDA_PYTHON: ${{ matrix.anaconda }}
      run: bash ./.github/workflows/build_env.sh
    - name: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: bash ./.github/workflows/run_test.sh
